spring.application.name=practice-nihongo

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/practice_nihongo_db?characterEncoding=UTF-8&allowEncodingChanges=true
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Character Encoding
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
spring.http.encoding.force-response=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.force-response=true

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Error Handling
server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=always
