version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: practice_nihongo_db
    environment:
      - POSTGRES_DB=practice_nihongo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - LANG=en_US.utf8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
